const mockRides = [
    {
      id: 1,
      driver: {
        name: "Alice Smith",
        avatar: "https://randomuser.me/api/portraits/women/1.jpg",
        rating: 4.9,
        trips: 120,
      },
      from: "San Francisco",
      to: "Los Angeles",
      date: "2024-03-15",
      time: "08:00 AM",
      price: 50,
      seats: 2,
      type: "solo",
      distance: "380 miles",
      duration: "6 hours",
      preferences: {
        smoking: false,
        pets: false,
        music: true,
      },
    },
    {
      id: 2,
      driver: {
        name: "Bob Johnson",
        avatar: "https://randomuser.me/api/portraits/men/2.jpg",
        rating: 4.7,
        trips: 98,
      },
      from: "Chicago",
      to: "Milwaukee",
      date: "2024-03-16",
      time: "01:30 PM",
      price: 30,
      seats: 4,
      type: "family",
      distance: "92 miles",
      duration: "1.5 hours",
      preferences: {
        smoking: true,
        pets: true,
        music: false,
      },
    },
    {
      id: 3,
      driver: {
        name: "Charlie Davis",
        avatar: "https://randomuser.me/api/portraits/men/3.jpg",
        rating: 4.8,
        trips: 75,
      },
      from: "Austin",
      to: "Dallas",
      date: "2024-03-18",
      time: "05:00 PM",
      price: 25,
      seats: 1,
      type: "business",
      distance: "195 miles",
      duration: "3 hours",
      preferences: {
        smoking: false,
        pets: false,
        music: true,
      },
    },
    {
      id: 4,
      driver: {
        name: "Diana Wilson",
        avatar: "https://randomuser.me/api/portraits/women/4.jpg",
        rating: 4.6,
        trips: 145,
      },
      from: "Seattle",
      to: "Portland",
      date: "2024-03-20",
      time: "10:00 AM",
      price: 40,
      seats: 3,
      type: "adventure",
      distance: "174 miles",
      duration: "2.5 hours",
      preferences: {
        smoking: true,
        pets: false,
        music: true,
      },
    },
    {
      id: 5,
      driver: {
        name: "Edward Brown",
        avatar: "https://randomuser.me/api/portraits/men/5.jpg",
        rating: 5.0,
        trips: 200,
      },
      from: "New York",
      to: "Philadelphia",
      date: "2024-03-22",
      time: "07:00 AM",
      price: 35,
      seats: 2,
      type: "solo",
      distance: "95 miles",
      duration: "1.5 hours",
      preferences: {
        smoking: false,
        pets: true,
        music: true,
      },
    },
  ];
  
  export default mockRides;
  